# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pingpong.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'pingpong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\"0\n\x0bPingRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\".\n\tPingReply\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x32\x33\n\x0fPingPongService\x12 \n\x04Ping\x12\x0c.PingRequest\x1a\n.PingReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pingpong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=18
  _globals['_PINGREQUEST']._serialized_end=66
  _globals['_PINGREPLY']._serialized_start=68
  _globals['_PINGREPLY']._serialized_end=114
  _globals['_PINGPONGSERVICE']._serialized_start=116
  _globals['_PINGPONGSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
