apiVersion: v1
kind: Pod
metadata:
  name: pingpong-server
  labels:
    app: pingpong-server
spec:
  containers:
  - name: server
    image: leejongwon2048/pingpong-test1:server
    imagePullPolicy: Always  # ← 반드시 추가!
    ports:
    - containerPort: 50051
